# Generated by Django 5.1.5 on 2025-04-18 18:46

import mapa_malvinas.models.choices.tipo_bloque
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapaBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('seccion', models.CharField(db_index=True, max_length=10)),
                ('numero', models.CharField(db_index=True, max_length=10)),
                ('numero_bloque', models.CharField(db_index=True, max_length=20)),
                ('descripcion', models.TextField()),
                ('coordenadas', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, choices=mapa_malvinas.models.choices.tipo_bloque.TipoBloque.get_all_tipos, max_length=50, null=True)),
            ],
        ),
    ]
