# Generated by Django 5.1.5 on 2025-02-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3d_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
