# Generated by Django 5.1.5 on 2025-02-11 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3d_app', '0003_car_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concesionaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='concesionaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m3d_app.concesionaria'),
        ),
    ]
