# Generated by Django 5.1.5 on 2025-02-28 05:27

import django.db.models.deletion
import m3d_app.models.choices.estado
import m3d_app.models.choices.provincia
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3d_app', '0004_concesionaria_car_concesionaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anios_experiencia', models.IntegerField(blank=True, null=True)),
                ('marcas_modelos_equipos', models.TextField(blank=True, null=True)),
                ('materiales_uso', models.TextField(blank=True, null=True)),
                ('cantidad_equipos', models.IntegerField(blank=True, null=True)),
                ('dimension_maxima_impresion', models.CharField(blank=True, max_length=50, null=True)),
                ('software_uso', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_institucion', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('piso_depto', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('particular', 'Particular'), ('institucion', 'Institución')], max_length=20)),
                ('como_se_entero', models.TextField(blank=True, null=True)),
                ('motivo_participacion', models.TextField(blank=True, null=True)),
                ('foto_validada', models.BooleanField(default=False)),
                ('diploma_entregado', models.BooleanField(default=False)),
                ('contactado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParticularSinImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suscriptor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='particular_sin_impresora', to='m3d_app.suscriptor')),
            ],
        ),
        migrations.CreateModel(
            name='ParticularConImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impresora', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='particular', to='m3d_app.impresora')),
                ('suscriptor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='particular_con_impresora', to='m3d_app.suscriptor')),
            ],
        ),
        migrations.CreateModel(
            name='NodoRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.IntegerField()),
                ('numero_bloque', models.CharField(max_length=20)),
                ('responsable_impresion', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('localidad', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(choices=m3d_app.models.choices.provincia.Provincia.get_all_provincias, max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nodo_seleccionado', models.CharField(choices=m3d_app.models.choices.provincia.Provincia.get_some_provincias, max_length=100)),
                ('detalles_nodo', models.TextField(blank=True, null=True)),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos_recepcion', to='m3d_app.suscriptor')),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionSinImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('dni_responsable', models.CharField(blank=True, max_length=20, null=True)),
                ('suscriptor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institucion_sin_impresora', to='m3d_app.suscriptor')),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionConImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('dni_responsable', models.CharField(blank=True, max_length=20, null=True)),
                ('impresora', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institucion', to='m3d_app.impresora')),
                ('suscriptor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institucion_con_impresora', to='m3d_app.suscriptor')),
            ],
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bloque', models.CharField(max_length=20, unique=True)),
                ('seccion', models.CharField(db_index=True, max_length=10)),
                ('numero', models.CharField(db_index=True, max_length=10)),
                ('estado', models.CharField(choices=m3d_app.models.choices.estado.Estado.get_all_estados, default='libre', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_nodo', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion_m3d', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_diploma', models.DateTimeField(blank=True, null=True)),
                ('historia_asociada', models.TextField(blank=True, null=True)),
                ('nodo_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques', to='m3d_app.nodorecepcion')),
                ('suscriptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='m3d_app.suscriptor')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Concesionaria',
        ),
    ]
