# Generated by Django 5.1.5 on 2025-05-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m3d_app", "0005_impresora_suscriptor_particularsinimpresora_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloque",
            name="nro_sorteo",
            field=models.IntegerField(
                blank=True,
                help_text="Número de sorteo asignado cuando el bloque tiene un suscriptor",
                null=True,
            ),
        ),
    ]
