# Generated by Django 5.1.5 on 2025-05-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m3d_app", "0006_add_nro_sorteo_to_bloque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloque",
            name="nro_sorteo",
            field=models.CharField(
                blank=True,
                help_text="Número de sorteo asignado cuando el bloque tiene un suscriptor",
                max_length=50,
                null=True,
            ),
        ),
    ]
